CREATE DATABASE University

USE University

CREATE TABLE Majors(
	MajorID INT NOT NULL,
	[Name] VARCHAR(64)
)

CREATE TABLE Students(
	StudentID INT NOT NULL,
	StudentNumber INT NOT NULL,
	StudentName VARCHAR(64),
	MajorID INT NOT NULL
)

CREATE TABLE Payments(
	PaymentID INT NOT NULL,
	PaymentDate DATE,
	PaymentAmount DECIMAL(5, 2),
	StudentID INT NOT NULL
)

CREATE TABLE Agenda(
	StudentID INT NOT NULL,
	SubjectID INT NOT NULL
)

CREATE TABLE Subjects(
	SubjectID INT NOT NULL,
	SubjectName VARCHAR(64)
)


ALTER TABLE Majors
	ADD CONSTRAINT PK_Mjors
	PRIMARY KEY (MajorID)

ALTER TABLE Students
	ADD CONSTRAINT PK_Students
	PRIMARY KEY (StudentID)

ALTER TABLE Students
	ADD CONSTRAINT FK_Students
	FOREIGN KEY(MajorID)
	REFERENCES Majors(MajorID)

ALTER TABLE Payments
	ADD CONSTRAINT PK_Payments
	PRIMARY KEY (PaymentID)

ALTER TABLE Payments
	ADD CONSTRAINT FK_Payments
	FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID)

ALTER TABLE Agenda
	ADD CONSTRAINT PK_Agenda
	PRIMARY KEY(StudentID, SubjectID)

ALTER TABLE Agenda
	ADD CONSTRAINT FK_AgendaStudents
	FOREIGN KEY (StudentID)
	REFERENCES Students(StudentID)

ALTER TABLE Subjects
	ADD CONSTRAINT PK_Subjects
	PRIMARY KEY (SubjectID)

ALTER TABLE Agenda
	ADD CONSTRAINT FK_AgendaSubjects
	FOREIGN KEY (SubjectID)
	REFERENCES Subjects(SubjectID)