CREATE DATABASE OnlineStore

USE OnlineStore

CREATE TABLE Orders(
	OrderID INT NOT NULL,
	CustomerID INT NOT NULL
	)


CREATE TABLE Customers(
	CustomerID INT NOT NULL,
	[Name] VARCHAR(50),
	Birthday DATE,
	CityID INT NOT NULL
	)

CREATE TABLE Cities(
	CityID INT NOT NULL,
	[Name] VARCHAR(50)
)


CREATE TABLE OrderItems(
	OrderID INT NOT NULL,
	ItemID INT NOT NULL
)


CREATE TABLE Items(
	ItemID INT NOT NULL,
	[Name] VARCHAR(50),
	ItemTypeID INT NOT NULL
)


CREATE TABLE ItemTypes(
	ItemTypeID INT NOT NULL,
	[Name] VARCHAR(50)
)

ALTER TABLE Orders
	ADD CONSTRAINT PK_Orders
	PRIMARY KEY(OrderID)

ALTER TABLE Customers
	ADD CONSTRAINT PK_Customers
	PRIMARY KEY (CustomerID)

ALTER TABLE Orders
	ADD CONSTRAINT FK_Orders
	FOREIGN KEY (CustomerID)
	REFERENCES Customers(CustomerID)


ALTER TABLE Cities
	ADD CONSTRAINT PK_Cities
	PRIMARY KEY (CityID)

ALTER TABLE Customers
	ADD CONSTRAINT FK_Customers
	FOREIGN KEY (CityID)
	REFERENCES Cities(CityID)



ALTER TABLE ItemTypes
	ADD CONSTRAINT PK_ItemTypes
	PRIMARY KEY (ItemTypeID)

ALTER TABLE Items 
	ADD CONSTRAINT PK_ItemID
	PRIMARY KEY (ItemID)

ALTER TABLE Items
	ADD CONSTRAINT FK_Items
	FOREIGN KEY (ItemTypeID)
	REFERENCES ItemTypes(ItemTypeID)

ALTER TABLE OrderItems
	ADD CONSTRAINT PK_OrderItems
	PRIMARY KEY (OrderID, ItemID)

ALTER TABLE OrderItems
	ADD CONSTRAINT FK_OrderItems
	FOREIGN KEY (OrderID)
	REFERENCES Orders(OrderID)

ALTER TABLE OrderItems
	ADD CONSTRAINT FK_ItemOrders
	FOREIGN KEY (ItemID)
	REFERENCES Items(ItemID)




